
[2025-02-05 18:09:56] INFO - exetest.py: 291

The path '/shared/nas2/xuehangg/syncbench_build/code/callee7/test_repo/src/_pytest/pytester.py' already exists.

[2025-02-05 18:09:56] INFO - callee_builder.py: 305

Using docker image with ID: 2ad0b81aebdc

[2025-02-05 18:09:56] INFO - exetest.py: 199

Repository already exists at `/shared/nas2/xuehangg/syncbench_build/code/callee7/test_repo/`.

Skipping repo clone...

[2025-02-05 18:09:56] INFO - aligner.py: 85

Successfully found and replaced the code of function/method `get_public_names` in the context_code.

[2025-02-05 18:09:56] INFO - tester.py: 51

Path already exists: /shared/nas2/xuehangg/syncbench_build/code/callee7/test_repo/src/_pytest/pytester.py

[2025-02-05 18:09:56] INFO - tester.py: 61

Successfully saved aligned_code to '/shared/nas2/xuehangg/syncbench_build/code/callee7/test_repo/src/_pytest/pytester.py'

[2025-02-05 18:09:56] INFO - tester.py: 368

Running unit test using file `/workspace/test_repo/testing/test_python_path.py` in Docker container `xuehang_7_pytest_container_get_public_names_Wed_Feb__5_18_09_56_2025`...

[2025-02-05 18:10:00] INFO - handler.py: 66

Folder /workspace/test_repo successfully copied to /shared/nas2/xuehangg/syncbench_build/code/caller16/test_repo/

[2025-02-05 18:10:00] ERROR - tester.py: 95

Execution failed with error: Command '['docker', 'run', '--rm', '--name', 'xuehang_9_sympy_container__test_Greedy_preprocess__Wed_Feb__5_18_09_52_2025', '-v', '/shared/nas2/xuehangg/syncbench_build/code/caller9/test_repo/sympy/polys/tests/test_polyoptions.py:/workspace/test_repo/sympy/polys/tests/test_polyoptions.py', '-w', '/workspace/test_repo', 'xuehang/9_sympy:3.11', '/bin/bash', '-c', 'export PYTHONPATH=$PYTHONPATH:/workspace/test_repo && /workspace/test_venv/bin/python -m pip install -e . && /workspace/test_venv/bin/python -m pytest -v /workspace/test_repo/sympy/polys/tests/test_polyoptions.py  ']' returned non-zero exit status 1.

[2025-02-05 18:10:00] ERROR - tester.py: 96

Error output:

[notice] A new release of pip is available: 24.2 -> 25.0
[notice] To update, run: python -m pip install --upgrade pip
/workspace/test_venv/lib/python3.11/site-packages/pytest_asyncio/plugin.py:208: PytestDeprecationWarning: The configuration option "asyncio_default_fixture_loop_scope" is unset.
The event loop scope for asynchronous fixtures will default to the fixture caching scope. Future versions of pytest-asyncio will default the loop scope for asynchronous fixtures to function scope. Set the default fixture loop scope explicitly in order to avoid unexpected behavior in the future. Valid fixture loop scopes are: "function", "class", "module", "package", "session"

  warnings.warn(PytestDeprecationWarning(_DEFAULT_FIXTURE_LOOP_SCOPE_UNSET))


[2025-02-05 18:10:00] ERROR - tester.py: 97

Standard output:
Obtaining file:///workspace/test_repo
  Installing build dependencies: started
  Installing build dependencies: finished with status 'done'
  Checking if build backend supports build_editable: started
  Checking if build backend supports build_editable: finished with status 'done'
  Getting requirements to build editable: started
  Getting requirements to build editable: finished with status 'done'
  Preparing editable metadata (pyproject.toml): started
  Preparing editable metadata (pyproject.toml): finished with status 'done'
Requirement already satisfied: mpmath>=1.1.0 in /workspace/test_venv/lib/python3.11/site-packages (from sympy==1.14.dev0) (1.3.0)
Building wheels for collected packages: sympy
  Building editable for sympy (pyproject.toml): started
  Building editable for sympy (pyproject.toml): finished with status 'done'
  Created wheel for sympy: filename=sympy-1.14.dev0-0.editable-py3-none-any.whl size=33243 sha256=e01a56afeba71034b0289623e2463ff1ce93254dfe27c3d412d5980b375b3f26
  Stored in directory: /tmp/pip-ephem-wheel-cache-2w15qnng/wheels/77/6d/8d/6d288ec591919a528b58517c67f4d12e0e98d23d266200ee38
Successfully built sympy
Installing collected packages: sympy
  Attempting uninstall: sympy
    Found existing installation: sympy 1.14.dev0
    Not uninstalling sympy at /workspace/test_repo, outside environment /workspace/test_venv
    Can't uninstall 'sympy'. No files were found to uninstall.
Successfully installed sympy-1.14.dev0
============================= test session starts ==============================
platform linux -- Python 3.11.9, pytest-8.3.2, pluggy-1.5.0 -- /workspace/test_venv/bin/python
cachedir: .pytest_cache
hypothesis profile 'sympy_hypothesis_profile' -> deadline=None, database=DirectoryBasedExampleDatabase(PosixPath('/workspace/test_repo/.hypothesis/examples'))
architecture: 64-bit
cache:        yes
ground types: python 

rootdir: /workspace/test_repo
configfile: pyproject.toml
plugins: hypothesis-6.112.0, doctestplus-1.2.1, split-0.9.0, timeout-2.3.1, xdist-3.6.1, asyncio-0.24.0
asyncio: mode=Mode.STRICT, default_loop_scope=None
collecting ... collected 46 items

sympy/polys/tests/test_polyoptions.py::test_Options_clone PASSED         [  2%]
sympy/polys/tests/test_polyoptions.py::test_Expand_preprocess PASSED     [  4%]
sympy/polys/tests/test_polyoptions.py::test_Expand_postprocess PASSED    [  6%]
sympy/polys/tests/test_polyoptions.py::test_Gens_preprocess PASSED       [  8%]
sympy/polys/tests/test_polyoptions.py::test_Gens_postprocess PASSED      [ 10%]
sympy/polys/tests/test_polyoptions.py::test_Wrt_preprocess PASSED        [ 13%]
sympy/polys/tests/test_polyoptions.py::test_Wrt_postprocess PASSED       [ 15%]
sympy/polys/tests/test_polyoptions.py::test_Sort_preprocess PASSED       [ 17%]
sympy/polys/tests/test_polyoptions.py::test_Sort_postprocess PASSED      [ 19%]
sympy/polys/tests/test_polyoptions.py::test_Order_preprocess PASSED      [ 21%]
sympy/polys/tests/test_polyoptions.py::test_Order_postprocess PASSED     [ 23%]
sympy/polys/tests/test_polyoptions.py::test_Field_preprocess PASSED      [ 26%]
sympy/polys/tests/test_polyoptions.py::test_Field_postprocess PASSED     [ 28%]
sympy/polys/tests/test_polyoptions.py::test_Greedy_preprocess FAILED     [ 30%]
sympy/polys/tests/test_polyoptions.py::test_Greedy_postprocess PASSED    [ 32%]
sympy/polys/tests/test_polyoptions.py::test_Domain_preprocess PASSED     [ 34%]
sympy/polys/tests/test_polyoptions.py::test_Domain_postprocess PASSED    [ 36%]
sympy/polys/tests/test_polyoptions.py::test_Split_preprocess PASSED      [ 39%]
sympy/polys/tests/test_polyoptions.py::test_Split_postprocess PASSED     [ 41%]
sympy/polys/tests/test_polyoptions.py::test_Gaussian_preprocess PASSED   [ 43%]
sympy/polys/tests/test_polyoptions.py::test_Gaussian_postprocess PASSED  [ 45%]
sympy/polys/tests/test_polyoptions.py::test_Extension_preprocess PASSED  [ 47%]
sympy/polys/tests/test_polyoptions.py::test_Extension_postprocess PASSED [ 50%]
sympy/polys/tests/test_polyoptions.py::test_Modulus_preprocess PASSED    [ 52%]
sympy/polys/tests/test_polyoptions.py::test_Modulus_postprocess PASSED   [ 54%]
sympy/polys/tests/test_polyoptions.py::test_Symmetric_preprocess PASSED  [ 56%]
sympy/polys/tests/test_polyoptions.py::test_Symmetric_postprocess PASSED [ 58%]
sympy/polys/tests/test_polyoptions.py::test_Strict_preprocess PASSED     [ 60%]
sympy/polys/tests/test_polyoptions.py::test_Strict_postprocess PASSED    [ 63%]
sympy/polys/tests/test_polyoptions.py::test_Auto_preprocess PASSED       [ 65%]
sympy/polys/tests/test_polyoptions.py::test_Auto_postprocess PASSED      [ 67%]
sympy/polys/tests/test_polyoptions.py::test_Frac_preprocess PASSED       [ 69%]
sympy/polys/tests/test_polyoptions.py::test_Frac_postprocess PASSED      [ 71%]
sympy/polys/tests/test_polyoptions.py::test_Formal_preprocess PASSED     [ 73%]
sympy/polys/tests/test_polyoptions.py::test_Formal_postprocess PASSED    [ 76%]
sympy/polys/tests/test_polyoptions.py::test_Polys_preprocess PASSED      [ 78%]
sympy/polys/tests/test_polyoptions.py::test_Polys_postprocess PASSED     [ 80%]
sympy/polys/tests/test_polyoptions.py::test_Include_preprocess PASSED    [ 82%]
sympy/polys/tests/test_polyoptions.py::test_Include_postprocess PASSED   [ 84%]
sympy/polys/tests/test_polyoptions.py::test_All_preprocess PASSED        [ 86%]
sympy/polys/tests/test_polyoptions.py::test_All_postprocess PASSED       [ 89%]
sympy/polys/tests/test_polyoptions.py::test_Gen_postprocess PASSED       [ 91%]
sympy/polys/tests/test_polyoptions.py::test_Symbols_preprocess PASSED    [ 93%]
sympy/polys/tests/test_polyoptions.py::test_Symbols_postprocess PASSED   [ 95%]
sympy/polys/tests/test_polyoptions.py::test_Method_preprocess PASSED     [ 97%]
sympy/polys/tests/test_polyoptions.py::test_Method_postprocess PASSED    [100%]

=================================== FAILURES ===================================
____________________________ test_Greedy_preprocess ____________________________

    def test_Greedy_preprocess():
        assert Greedy.preprocess(False) is False
        assert Greedy.preprocess(True) is True
    
        assert Greedy.preprocess(0) is False
        assert Greedy.preprocess(1) is True
    
>       raises(OptionError, "Greedy.preprocess(x)")
E       TypeError: 'Greedy.preprocess(x)' object (type: <class 'str'>) must be callable

sympy/polys/tests/test_polyoptions.py:149: TypeError
                                DO *NOT* COMMIT!                                
=========================== short test summary info ============================
FAILED sympy/polys/tests/test_polyoptions.py::test_Greedy_preprocess - TypeEr...
========================= 1 failed, 45 passed in 0.45s =========================


[2025-02-05 18:10:00] INFO - handler.py: 66

[2025-02-05 18:10:00] INFO - tester.py: 257

Folder /workspace/test_repo successfully copied to /shared/nas2/xuehangg/syncbench_build/code/caller21/21_mlflow/

{'total': 46, 'passed': 45, 'xpassed': 0, 'failed': 1, 'xfailed': 0, 'deselected': 0, 'skipped': 0, 'warning': 0, 'error': 0}

[2025-02-05 18:10:00] INFO - tester.py: 436

Number of test evals in current unit test: 46

[2025-02-05 18:10:00] INFO - tester.py: 66

Stopping and removing container 'xuehang_9_sympy_container__test_Greedy_preprocess__Wed_Feb__5_18_09_52_2025'...

[2025-02-05 18:10:00] INFO - handler.py: 77

Container xuehang_16_pillow_3.11__Wed__Feb____5__18_09_54__2025__test_repo__dockerhandler_attempt1 stopped and removed successfully.

[2025-02-05 18:10:00] INFO - exetest.py: 210

Repository cloned from docker image to `/shared/nas2/xuehangg/syncbench_build/code/caller16/test_repo/`

[2025-02-05 18:10:00] INFO - aligner.py: 85

Successfully found and replaced the code of function/method `test_1px_width` in the context_code.

[2025-02-05 18:10:00] INFO - handler.py: 77

Container xuehang_21_mlflow_3.11__Wed__Feb____5__18_09_42__2025__test_repo__dockerhandler_attempt1 stopped and removed successfully.

[2025-02-05 18:10:00] INFO - exetest.py: 210

Repository cloned from docker image to `/shared/nas2/xuehangg/syncbench_build/code/caller21/21_mlflow/`

Successfully removed container 'xuehang_9_sympy_container__test_Greedy_preprocess__Wed_Feb__5_18_09_52_2025'

[2025-02-05 18:10:00] INFO - exetest.py: 291

The path '/shared/nas2/xuehangg/syncbench_build/code/caller16/test_repo/Tests/test_file_pcx.py' already exists.

[2025-02-05 18:10:00] INFO - caller_builder.py: 310

Using docker image with ID: fc29e8ee0f09

[2025-02-05 18:10:00] INFO - exetest.py: 199

Repository already exists at `/shared/nas2/xuehangg/syncbench_build/code/caller16/test_repo/`.

Skipping repo clone...

[2025-02-05 18:10:00] INFO - aligner.py: 85

Successfully found and replaced the code of function/method `test_1px_width` in the context_code.

Update: Commit tracing success!

[2025-02-05 18:10:00] INFO - tester.py: 51

Path already exists: /shared/nas2/xuehangg/syncbench_build/code/caller16/test_repo/Tests/test_file_pcx.py

[2025-02-05 18:10:00] INFO - tester.py: 61

Successfully saved aligned_code to '/shared/nas2/xuehangg/syncbench_build/code/caller16/test_repo/Tests/test_file_pcx.py'

[2025-02-05 18:10:00] INFO - tester.py: 368

Running unit test using file `/workspace/test_repo/Tests/test_file_pcx.py` in Docker container `xuehang_16_pillow_container__test_1px_width__Wed_Feb__5_18_10_00_2025`...

[2025-02-05 18:10:01] INFO - tester.py: 92

Execution succeeded!
Container output: 
Obtaining file:///workspace/test_repo
  Installing build dependencies: started
  Installing build dependencies: finished with status 'done'
  Checking if build backend supports build_editable: started
  Checking if build backend supports build_editable: finished with status 'done'
  Getting requirements to build editable: started
  Getting requirements to build editable: finished with status 'done'
  Preparing editable metadata (pyproject.toml): started
  Preparing editable metadata (pyproject.toml): finished with status 'done'
Requirement already satisfied: iniconfig in /workspace/test_venv/lib/python3.11/site-packages (from pytest==8.4.0.dev64+g72c682ff9.d20250206) (2.0.0)
Requirement already satisfied: packaging in /workspace/test_venv/lib/python3.11/site-packages (from pytest==8.4.0.dev64+g72c682ff9.d20250206) (24.1)
Requirement already satisfied: pluggy<2,>=1.5 in /workspace/test_venv/lib/python3.11/site-packages (from pytest==8.4.0.dev64+g72c682ff9.d20250206) (1.5.0)
Building wheels for collected packages: pytest
  Building editable for pytest (pyproject.toml): started
  Building editable for pytest (pyproject.toml): finished with status 'done'
  Created wheel for pytest: filename=pytest-8.4.0.dev64+g72c682ff9.d20250206-0.editable-py3-none-any.whl size=9450 sha256=e5a7a97d4edb5ca62169f3d45201369069a21811391debafb78fdd5d42f97638
  Stored in directory: /tmp/pip-ephem-wheel-cache-au2poecz/wheels/77/6d/8d/6d288ec591919a528b58517c67f4d12e0e98d23d266200ee38
Successfully built pytest
Installing collected packages: pytest
  Attempting uninstall: pytest
    Found existing installation: pytest 8.4.0.dev64+g72c682ff9
    Uninstalling pytest-8.4.0.dev64+g72c682ff9:
      Successfully uninstalled pytest-8.4.0.dev64+g72c682ff9
Successfully installed pytest-8.4.0.dev64+g72c682ff9.d20250206
============================= test session starts ==============================
platform linux -- Python 3.11.9, pytest-8.4.0.dev64+g72c682ff9.d20250206, pluggy-1.5.0 -- /workspace/test_venv/bin/python
cachedir: .pytest_cache
rootdir: /workspace/test_repo
configfile: pyproject.toml
plugins: asyncio-0.24.0
asyncio: mode=Mode.STRICT, default_loop_scope=None
collecting ... collected 6 items

testing/test_python_path.py::test_one_dir PASSED                         [ 16%]
testing/test_python_path.py::test_two_dirs PASSED                        [ 33%]
testing/test_python_path.py::test_local_plugin PASSED                    [ 50%]
testing/test_python_path.py::test_module_not_found PASSED                [ 66%]
testing/test_python_path.py::test_no_ini PASSED                          [ 83%]
testing/test_python_path.py::test_clean_up PASSED                        [100%]

============================== 6 passed in 0.34s ===============================


[2025-02-05 18:10:01] INFO - tester.py: 257

{'total': 6, 'passed': 6, 'xpassed': 0, 'failed': 0, 'xfailed': 0, 'deselected': 0, 'skipped': 0, 'warning': 0, 'error': 0}

[2025-02-05 18:10:01] INFO - tester.py: 436

Number of test evals in current unit test: 6

[2025-02-05 18:10:01] INFO - tester.py: 66

Stopping and removing container 'xuehang_7_pytest_container_get_public_names_Wed_Feb__5_18_09_56_2025'...

Successfully removed container 'xuehang_7_pytest_container_get_public_names_Wed_Feb__5_18_09_56_2025'

[2025-02-05 18:10:01] INFO - exetest.py: 155

Successfully removed target directory at '/shared/nas2/xuehangg/syncbench_build/code/caller9/test_repo/'

[2025-02-05 18:10:01] INFO - tester.py: 79

Removing temporary directory used for repository at '/shared/nas2/xuehangg/syncbench_build/code/caller9/test_repo/'

[2025-02-05 18:10:01] INFO - caller_builder.py: 490

[Execution Test for 'original_code + new_context'] Failed


[2025-02-05 18:10:01] INFO - caller_builder.py: 699

[2025-02-05 18:10:01] INFO - caller_builder.py: 548

[Valid test 436/436] Current commit(38ec67fc517e33af110de4cb7b9c3b0b18ea0f88) has been successfully recorded.

[2025-02-05 18:10:02] INFO - exetest.py: 155

Successfully removed target directory at '/shared/nas2/xuehangg/syncbench_build/code/callee7/test_repo/'

[2025-02-05 18:10:02] INFO - tester.py: 79

Removing temporary directory used for repository at '/shared/nas2/xuehangg/syncbench_build/code/callee7/test_repo/'

[2025-02-05 18:10:02] INFO - callee_builder.py: 480

[Execution Test for 'gold_code + new_context'] Passed


[2025-02-05 18:10:02] INFO - callee_builder.py: 297

Preparing docker env for execution test...

[2025-02-05 18:10:02] WARNING - callee_builder.py: 123

Failed to remove file `/shared/nas2/xuehangg/syncbench_build/code/callee7/7_pytest/.git/objects/pack/.nfs000000000c5282bf000121e7`: [Errno 16] Device or resource busy: '/shared/nas2/xuehangg/syncbench_build/code/callee7/7_pytest/.git/objects/pack/.nfs000000000c5282bf000121e7'
Attempting file removal again...

[2025-02-05 18:10:02] WARNING - callee_builder.py: 123

Failed to remove file `/shared/nas2/xuehangg/syncbench_build/code/callee7/7_pytest/.git/objects/pack/.nfs000000000c52912b000121e8`: [Errno 16] Device or resource busy: '/shared/nas2/xuehangg/syncbench_build/code/callee7/7_pytest/.git/objects/pack/.nfs000000000c52912b000121e8'
Attempting file removal again...

[2025-02-05 18:10:02] WARNING - callee_builder.py: 130

Failed to remove directory `/shared/nas2/xuehangg/syncbench_build/code/callee7/7_pytest/.git/objects/pack`: [Errno 39] Directory not empty: '/shared/nas2/xuehangg/syncbench_build/code/callee7/7_pytest/.git/objects/pack'
Attempting directory removal again...

[2025-02-05 18:10:02] WARNING - callee_builder.py: 130

Failed to remove directory `/shared/nas2/xuehangg/syncbench_build/code/callee7/7_pytest/.git/objects`: [Errno 39] Directory not empty: '/shared/nas2/xuehangg/syncbench_build/code/callee7/7_pytest/.git/objects'
Attempting directory removal again...

[2025-02-05 18:10:02] WARNING - callee_builder.py: 130

Failed to remove directory `/shared/nas2/xuehangg/syncbench_build/code/callee7/7_pytest/.git`: [Errno 39] Directory not empty: '/shared/nas2/xuehangg/syncbench_build/code/callee7/7_pytest/.git'
Attempting directory removal again...

[2025-02-05 18:10:02] WARNING - callee_builder.py: 130

Failed to remove directory `/shared/nas2/xuehangg/syncbench_build/code/callee7/7_pytest`: [Errno 39] Directory not empty: '/shared/nas2/xuehangg/syncbench_build/code/callee7/7_pytest'
Attempting directory removal again...

[2025-02-05 18:10:02] INFO - callee_builder.py: 134

Successfully removed directory at '/shared/nas2/xuehangg/syncbench_build/code/callee7/'

[2025-02-05 18:10:02] INFO - builder.py: 176

Checking if Docker image 'xuehang/7_pytest' exists...

Docker image 'xuehang/7_pytest' already exists with ID: 2ad0b81aebdc

[2025-02-05 18:10:02] INFO - handler.py: 30

Successfiully created local path: `/shared/nas2/xuehangg/syncbench_build/code/callee7/test_repo/`

[2025-02-05 18:10:02] INFO - caller_builder.py: 276

Successfully saved data to '/shared/nas2/xuehangg/syncbench_build/dataset/caller_9_sympy.json

Current progress successfully saved to '/shared/nas2/xuehangg/syncbench_build/dataset/caller_9_sympy.json'


[2025-02-05 18:10:02] INFO - caller_builder.py: 699


=========================  Function/method filtering 15/46: [test_polyoptions.py] -> [test_polyoptions.py] -> [test_Greedy_postprocess]  =========================

[2025-02-05 18:10:02] WARNING - caller_builder.py: 392

An error occurred when tracing commit history: /shared/nas2/xuehangg/syncbench_build/code/caller9/9_sympy
Attemptaining again...

[2025-02-05 18:10:02] INFO - builder.py: 176

Checking if Docker image 'xuehang/9_sympy' exists...

Docker image 'xuehang/9_sympy' already exists with ID: 75594250eeb0

[2025-02-05 18:10:02] INFO - exetest.py: 199

Repository already exists at `/shared/nas2/xuehangg/syncbench_build/code/caller9/9_sympy/`.

Removing existing repo and re-cloning...

[2025-02-05 18:10:02] WARNING - exetest.py: 144

Failed to remove file /shared/nas2/xuehangg/syncbench_build/code/caller9/9_sympy/.git/objects/pack/.nfs000000000c5201e4000121e3: [Errno 16] Device or resource busy: '/shared/nas2/xuehangg/syncbench_build/code/caller9/9_sympy/.git/objects/pack/.nfs000000000c5201e4000121e3'
Attempting to remove file /shared/nas2/xuehangg/syncbench_build/code/caller9/9_sympy/.git/objects/pack/.nfs000000000c5201e4000121e3 again...

[2025-02-05 18:10:02] WARNING - exetest.py: 144

Failed to remove file /shared/nas2/xuehangg/syncbench_build/code/caller9/9_sympy/.git/objects/pack/.nfs000000000c52202d000121e2: [Errno 16] Device or resource busy: '/shared/nas2/xuehangg/syncbench_build/code/caller9/9_sympy/.git/objects/pack/.nfs000000000c52202d000121e2'
Attempting to remove file /shared/nas2/xuehangg/syncbench_build/code/caller9/9_sympy/.git/objects/pack/.nfs000000000c52202d000121e2 again...

[2025-02-05 18:10:02] WARNING - exetest.py: 151

Failed to remove directory /shared/nas2/xuehangg/syncbench_build/code/caller9/9_sympy/.git/objects/pack: [Errno 39] Directory not empty: '/shared/nas2/xuehangg/syncbench_build/code/caller9/9_sympy/.git/objects/pack'
Attempting to remove directory /shared/nas2/xuehangg/syncbench_build/code/caller9/9_sympy/.git/objects/pack again...

[2025-02-05 18:10:02] WARNING - exetest.py: 151

Failed to remove directory /shared/nas2/xuehangg/syncbench_build/code/caller9/9_sympy/.git/objects: [Errno 39] Directory not empty: '/shared/nas2/xuehangg/syncbench_build/code/caller9/9_sympy/.git/objects'
Attempting to remove directory /shared/nas2/xuehangg/syncbench_build/code/caller9/9_sympy/.git/objects again...

[2025-02-05 18:10:02] WARNING - exetest.py: 151

Failed to remove directory /shared/nas2/xuehangg/syncbench_build/code/caller9/9_sympy/.git: [Errno 39] Directory not empty: '/shared/nas2/xuehangg/syncbench_build/code/caller9/9_sympy/.git'
Attempting to remove directory /shared/nas2/xuehangg/syncbench_build/code/caller9/9_sympy/.git again...

[2025-02-05 18:10:02] INFO - exetest.py: 155

Successfully removed target directory at '/shared/nas2/xuehangg/syncbench_build/code/caller9/9_sympy/'

[2025-02-05 18:10:02] INFO - handler.py: 22

The local path '/shared/nas2/xuehangg/syncbench_build/code/caller9/9_sympy/' already exists.

[2025-02-05 18:10:02] INFO - handler.py: 42

Container xuehang_7_pytest_3.11__Wed__Feb____5__18_10_02__2025__test_repo__dockerhandler_attempt1 started successfully.

[2025-02-05 18:10:02] INFO - handler.py: 42

Container xuehang_9_sympy_3.11__Wed__Feb____5__18_10_02__2025__test_repo__dockerhandler_attempt1 started successfully.

[2025-02-05 18:10:05] INFO - handler.py: 66

Folder /workspace/test_repo successfully copied to /shared/nas2/xuehangg/syncbench_build/code/callee7/test_repo/

[2025-02-05 18:10:05] INFO - handler.py: 77

Container xuehang_7_pytest_3.11__Wed__Feb____5__18_10_02__2025__test_repo__dockerhandler_attempt1 stopped and removed successfully.

[2025-02-05 18:10:05] INFO - exetest.py: 210

Repository cloned from docker image to `/shared/nas2/xuehangg/syncbench_build/code/callee7/test_repo/`

[2025-02-05 18:10:05] INFO - aligner.py: 85

Successfully found and replaced the code of function/method `get_public_names` in the context_code.

[2025-02-05 18:10:05] INFO - exetest.py: 291

The path '/shared/nas2/xuehangg/syncbench_build/code/callee7/test_repo/src/_pytest/pytester.py' already exists.

[2025-02-05 18:10:05] INFO - callee_builder.py: 305

Using docker image with ID: 2ad0b81aebdc

[2025-02-05 18:10:05] INFO - exetest.py: 199

Repository already exists at `/shared/nas2/xuehangg/syncbench_build/code/callee7/test_repo/`.

Skipping repo clone...

[2025-02-05 18:10:05] INFO - aligner.py: 85

Successfully found and replaced the code of function/method `get_public_names` in the context_code.

[2025-02-05 18:10:05] INFO - tester.py: 51

Path already exists: /shared/nas2/xuehangg/syncbench_build/code/callee7/test_repo/src/_pytest/pytester.py

[2025-02-05 18:10:05] INFO - tester.py: 61

Successfully saved aligned_code to '/shared/nas2/xuehangg/syncbench_build/code/callee7/test_repo/src/_pytest/pytester.py'

[2025-02-05 18:10:05] INFO - tester.py: 368

Running unit test using file `/workspace/test_repo/testing/test_python_path.py` in Docker container `xuehang_7_pytest_container_get_public_names_Wed_Feb__5_18_10_05_2025`...

[2025-02-05 18:10:07] INFO - handler.py: 66

Folder /workspace/test_repo successfully copied to /shared/nas2/xuehangg/syncbench_build/code/callee21/test_repo/

[2025-02-05 18:10:07] INFO - handler.py: 77

Container xuehang_21_mlflow_3.11__Wed__Feb____5__18_09_50__2025__test_repo__dockerhandler_attempt1 stopped and removed successfully.

[2025-02-05 18:10:07] INFO - exetest.py: 210

Repository cloned from docker image to `/shared/nas2/xuehangg/syncbench_build/code/callee21/test_repo/`

[2025-02-05 18:10:07] INFO - aligner.py: 85

Successfully found and replaced the code of function/method `invalid_parameter_value` in the context_code.

[2025-02-05 18:10:07] INFO - exetest.py: 291

The path '/shared/nas2/xuehangg/syncbench_build/code/callee21/test_repo/mlflow/exceptions.py' already exists.

[2025-02-05 18:10:07] INFO - callee_builder.py: 305

Using docker image with ID: 73f308f5c08c

[2025-02-05 18:10:07] INFO - exetest.py: 199

Repository already exists at `/shared/nas2/xuehangg/syncbench_build/code/callee21/test_repo/`.

Skipping repo clone...

[2025-02-05 18:10:07] INFO - aligner.py: 85

Successfully found and replaced the code of function/method `invalid_parameter_value` in the context_code.

[2025-02-05 18:10:07] INFO - tester.py: 51

Path already exists: /shared/nas2/xuehangg/syncbench_build/code/callee21/test_repo/mlflow/exceptions.py

[2025-02-05 18:10:07] INFO - tester.py: 61

Successfully saved aligned_code to '/shared/nas2/xuehangg/syncbench_build/code/callee21/test_repo/mlflow/exceptions.py'

[2025-02-05 18:10:07] INFO - tester.py: 368

Running unit test using file `/workspace/test_repo/tests/pyfunc/test_model_export_with_loader_module_and_data_path.py` in Docker container `xuehang_21_mlflow_container__invalid_parameter_value__Wed_Feb__5_18_10_07_2025`...
